# config file for Hierarchical Perceiver
in_channels: 3
image_size: 32
n_classes: 10

start_dim: 16
blocks_cfgs:
  # block 1
  - input_dim: 16   # must be the same as `start_dim`
    groups: 4
    sa_layers: 2
    heads: 2
    latent_dim: 32
    n_latents: 64
  # block 2
  - input_dim: 32
    groups: 2
    sa_layers: 2
    heads: 4
    latent_dim: 64
    n_latents: 64
  # block 3
  - input_dim: 64
    groups: 1
    sa_layers: 4
    heads: 8
    latent_dim: 128
    n_latents: 64
  # block 4
  - input_dim: 128
    groups: 1
    sa_layers: 2
    heads: 8
    latent_dim: 128
    n_latents: 32
