# config file for Hierarchical Perceiver
in_channels: 3
image_size: 32
n_classes: 10

start_dim: 16
blocks_cfgs:
  # block 1
  - in_dim: 16      # must be the same as `start_dim`
    latent_dim: 32    # `latent_dim` must be divisible by `latent_heads`
    latent_heads: 2
    groups: 4
    n_latents: 64
    sa_layers: 2
    dropout: 0.1
  # block 2
  - in_dim: 32
    latent_dim: 64
    latent_heads: 4
    groups: 2
    n_latents: 64
    sa_layers: 2
    dropout: 0.1
  # block 3
  - in_dim: 64
    latent_dim: 128
    latent_heads: 8
    groups: 1
    n_latents: 64
    sa_layers: 4
    dropout: 0.1
