# config file for ViT
in_channels: 3
image_size: 32
n_classes: 10

patch_size: 8
depth: 12       # depth of transformer encoder
dim: 32         # dimension of linear projection
heads: 4        # number of heads for multi-headed self-attention
dim_head: 32    # dimension of q,k,v per head
dropout: 0.     # dropout rate for transformer encoder